services:
  - type: web
    name: khmer-luna-date
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:production
    envVars:
      - key: NODE_ENV
        value: production
